version: "2"
services:
    neo4j:
      image: neo4j:3.2.1
      restart: on-failure
      ports:
       - "17474:7474"
       - "7687:7687"
      environment:
        - NEO4J_AUTH=none
    pgdb:
      image: postgres:9.6.3
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres1
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: pursume
    web:
      build: .
      ports:
        - "3333:3333"
      depends_on:
        - pgdb
      environment:
        SEQ_DB: pursume
        SEQ_USER: postgres1
        SEQ_PW: postgres
        PORT: 5432
        DATABASE_URL: postgres://postgres1:postgres@pg:5432?sslmode=disable
